services:
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html
      - ./sql:/var/www/db  
    networks:
      - ctf_net
    depends_on: []
  
networks:
  ctf_net:
    driver: bridge

volumes:
  db_data: 

