services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ctf_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ctf_net

  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - ctf_net

  challenge4:
    build: ./CTF_challenge/CTF4
    restart: unless-stopped
    ports:
      - "1004:80"
    depends_on:
      - db
    volumes:
      - ./CTF_challenge/CTF4/resource:/var/www/html
    networks:
      - ctf_net

  challenge5:
    build: ./CTF_challenge/CTF5
    restart: unless-stopped
    ports:
      - "1005:80"
    depends_on:
      - db
    volumes:
      - ./CTF_challenge/CTF5/resource:/var/www/html
    networks:
      - ctf_net
 
networks:
  ctf_net:
    driver: bridge

volumes:
  db_data:
