services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ctf_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ctf_net

  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - ctf_net

  challenge1:
    build: ./src/CTF_challenge/CTF1
    restart: unless-stopped
    ports:
      - "1001:80"
    depends_on:
      - db
    volumes:
      - ./src/CTF_challenge/CTF1:/var/www/html
    networks:
      - ctf_net

  challenge2:
    build: ./src/CTF_challenge/CTF2
    restart: unless-stopped
    ports:
      - "1002:80"
    depends_on:
      - db
    volumes:
      - ./src/CTF_challenge/CTF2:/var/www/html
    networks:
      - ctf_net

  challenge3:
    build: ./src/CTF_challenge/CTF3
    restart: unless-stopped
    ports:
      - "1003:80"
    depends_on:
      - db
    volumes:
      - ./src/CTF_challenge/CTF3:/var/www/html
    networks:
      - ctf_net

  challenge4:
    build: ./src/CTF_challenge/CTF4
    restart: unless-stopped
    ports:
      - "1004:80"
    depends_on:
      - db
    volumes:
      - ./src/CTF_challenge/CTF4:/var/www/html
    networks:
      - ctf_net

  challenge5:
    build: ./src/CTF_challenge/CTF5
    restart: unless-stopped
    ports:
      - "1005:80"
    depends_on:
      - db
    volumes:
      - ./src/CTF_challenge/CTF5:/var/www/html
    networks:
      - ctf_net
 
networks:
  ctf_net:
    driver: bridge

volumes:
  db_data:
