services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ctf_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ctf_net

  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - ctf_net
            
networks:
  ctf_net:
    driver: bridge

volumes:
  db_data:
