services:
  lan_4:
    build: ./CTF4
    restart: unless-stopped
    ports:
      - "1004:80"
    volumes:
      - ./CTF2/resource:/var/www/html
    networks:
      - ctf_net

networks:
  ctf_net:
    driver: bridge
