services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: ctf_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"   #can change 3307 to another port if it is already in use
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ctf_net

  app:
    build: .
    ports:
      - "5000:80"    #can change 5000 to another port if it is already in use
    depends_on:
      - db
    volumes:
      - ./UI_data:/var/www/html
    networks:
      - ctf_net

networks:
  ctf_net:
    driver: bridge

volumes:
  db_data:



#commad: docker-compose build: build the container
#        docker-compose up  : run the container
#        docker-compose down : used to stop containers and delete everything created by docker-compose
#        docker-compose restart db :  used to restart the db container
#attention: It something change in the  docker-compose file, you need to rebuild down-->up 

